### ISSUE TITLE
Manifest merger failed : Apps targeting Android 12 - Android Studio Error 

### ISSUE THREAD

**Issue by TakmingMark** [naver/naveridlogin-sdk-android#18] opened 2021-12-17 08:08 UTC
My android project target sdk upgrade to 31, and discover this problem,

and I found this problem in latest version 4.2.6

```
<activity
            android:name="com.nhn.android.naverlogin.ui.OAuthCustomTabActivity"
            android:configChanges="orientation|screenSize"
            android:launchMode="singleTask"
            android:theme="@android:style/Theme.Translucent.NoTitleBar" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <!-- Intent URL 에서 로그인 액티비티를 실행하기 위해 설정 -->
                <data
                    android:host="authorize"
                    android:path="/"
                    android:scheme="naver3rdpartylogin" />
            </intent-filter>
        </activity>
```

I think it need to add android :exported=true in activity.

**Comment by qb20nh** [comment] 2022-01-11 10:46
Duplicate of #14

**Comment by mydamyda** [comment] 2022-01-24 15:44
Hello, @TakmingMark.

I've been responding since **v5.0.0** of Naver Id Login SDK.

Regards,
Namhoon.

**Closed by mydamyda** 2022-01-24 15:44 UTC
Labels: Bug
